### ISSUE TITLE
Which harfbuz shared library version should be used with harfpy?

### ISSUE THREAD

**Issue by signalarun** [ldo/harfpy#1]
When run I am receiving function not found error.

**Comment by ldo** [comment]
On Debian:

    ldo@theon:~> dpkg-query -L libharfbuzz0b
    /.
    /usr
    /usr/lib
    /usr/lib/x86_64-linux-gnu
    /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0.10200.7
    /usr/share
    /usr/share/doc
    /usr/share/doc/libharfbuzz0b
    /usr/share/doc/libharfbuzz0b/TODO
    /usr/share/doc/libharfbuzz0b/changelog.Debian.amd64.gz
    /usr/share/doc/libharfbuzz0b/changelog.Debian.gz
    /usr/share/doc/libharfbuzz0b/changelog.gz
    /usr/share/doc/libharfbuzz0b/copyright
    /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0

What is the HarfBuzz package on your distro?

**Comment by signalarun** [comment]
Harf Buzz 1.4.1

**Comment by ldo** [comment]
Is it a Debian derivative? What does `dpkg-query -L libharfbuzz0b` report for you?

**Comment by signalarun** [comment]
Just compiled it from source. The error was obtained when the lib is
accessed from harfpy python code.

**Comment by ldo** [comment]
So it should be in `/usr/local/lib` somewhere—Python should still pick it up. Where did it install?

**Comment by ldo** [comment]
No further response.
