### ISSUE TITLE
Proposal: “universal” text shaping result JSON notation based on hb-shape

### ISSUE THREAD

**Issue by twardoch** [ldo/harfpy#10]
See: https://github.com/OpenType/opentype-layout/issues/4

(Apologies for "spamming".)

**Comment by ldo** [comment]
Is this something I need to do? Presumably if/when it is added to HarfBuzz at some point, then I can follow with an appropriate wrapper.

**Comment by khaledhosny** [comment]
HarfBuzz already support this, the `hb_buffer_serialize_*` stuff.

**Comment by ldo** [comment]
And HarfPy already wraps these calls.
