### ISSUE TITLE
Support for MCUs?

### ISSUE THREAD

**Issue by arahasya** [ldo/harfpy#15]
Hi,

I have a very important project to render Devnagiri text using Arduino Uno/Mega or ESP32.

I was looking for solutions and came across this. As you have clearly mentioned this library is for linux environment. 

But the code is in python. ESP32 supports micro python.

Is there any way to port this to ESP32/Arduino environment with MicroPython?

If not, do you have any ideas how to achieve this? Thanks!

**Comment by ldo** [comment]
I have no idea. Does MicroPython include the ctypes library? That and libharfbuzz should be the main dependencies.

**Comment by ldo** [comment]
Nothing more?
