### ISSUE TITLE
64 scale factor should only apply to FT funcs

### ISSUE THREAD

**Issue by adrientetar** [ldo/harfpy#3]
So I did port the hb_ot python example from the harfbuzz repo:

~~~python
import array
import os

from harfbuzz import HARFBUZZ as HB
import harfbuzz as hb

def shape_dat(path, text):
    a = array.array('B')
    size = os.path.getsize(path)
    with open(path, 'rb') as f:
        a.fromfile(f, size)

    blob = hb.Blob.create_for_array(a, HB.MEMORY_MODE_READONLY)
    face = hb.Face.create(blob, 0)
    del blob
    font = hb.Font.create(face)
    upem = face.upem
    del face
    font.scale = (upem, upem)
    font.ot_set_funcs()

    buf = hb.Buffer.create()
    class Debugger(object):
        def message(self, buf, font, msg, data):
            print(msg)
            return True
    debugger = Debugger()
    #buf.set_message_func(debugger, None, None)

    buf.add_str(text)
    buf.guess_segment_properties()
    hb.shape(font, buf)

    for info, pos in zip(buf.glyph_infos, buf.glyph_positions):
        gid = info.codepoint
        cluster = info.cluster
        x_advance = pos.x_advance
        x_offset = pos.x_offset
        y_offset = pos.y_offset

        print("gid%d=%d@%d,%d+%d" % (
            gid, cluster, x_advance, x_offset, y_offset))

if __name__ == "__main__":
    import sys
    assert len(sys.argv) == 3
    shape_dat(*sys.argv[1:])
~~~

Yet the x_advance values that I get back seem very small, e.g. with Bitstream Vera:

~~~
PS C:\Users\Admin\Documents> python harfbuzz__.py C:\Vera.ttf "Hello World!"
gid43=0@24,0+0
gid72=1@19,0+0
gid79=2@8,0+0
gid79=3@8,0+0
gid82=4@19,0+0
gid3=5@10,0+0
gid58=6@31,0+0
gid82=7@19,0+0
gid85=8@13,0+0
gid79=9@8,0+0
gid71=10@20,0+0
gid4=11@12,0+0
~~~

Is this expected?

cc @khaledhosny

**Comment by khaledhosny** [comment]
Looks like all glyph positions are divided by 64, but the code that set font scale does not multiply it by 64. I think the division by 64 should be kept only for when FreeType font functions are used (that I assume multiply the font size by 64).

**Comment by khaledhosny** [comment]
Or I guess the Font.scale setter can just call HARFBUZZ.to_position_t() on the value being set.

**Comment by ldo** [comment]
I forgot about non-FreeType fonts. Looks like I need to distinguish FreeType and non-FreeType cases. This will have ramifications through the `Face`, `Font` and `FontFuncs` classes.

I may need to make a backward-incompatible change to the API for `FontFuncs`.

Got to think some more about this.

**Comment by ldo** [comment]
OK, I have done a change to the `Font.scale` attribute to be consistent with the other metrics. Here is the output I now get from running your script:

    gid43=0@1540,0+0
    gid72=1@1260,0+0
    gid79=2@569,0+0
    gid79=3@569,0+0
    gid82=4@1253,0+0
    gid3=5@651,0+0
    gid58=6@2025,0+0
    gid82=7@1253,0+0
    gid85=8@842,0+0
    gid79=9@569,0+0
    gid71=10@1300,0+0
    gid4=11@821,0+0

I still plan to make a backward-incompatible API change to allow more control over the metrics scaling.

**Comment by ldo** [comment]
OK, I have committed in d88fbb2 the necessary reworking of all the handling of metrics. Note the new `autoscale` setting which is automatically set to `True` for FreeType faces, and which you now have to specify for non-FreeType ones and for `FontFunc` objects.

I think this properly solves the problem. Unless I misunderstood something about FreeType fonts...

**Comment by adrientetar** [comment]
> and which you now have to specify for non-FreeType ones and for FontFunc objects.

Maybe that argument could have a default value of False?

**Comment by ldo** [comment]
Is this whole autoscale business appropriate at all? Or should I get rid of it?

**Comment by adrientetar** [comment]
Can be removed I think. I'm not using it, I don't use FT funcs.

**Comment by khaledhosny** [comment]
I think it is surprising at least, especially if one is familiar with the C API.

**Comment by ldo** [comment]
The 26.6 scaling is done to be consistent with FreeType. When you call FreeType’s `FT_Set_Char_Size`, you set the size in 26.6-scaled units. Therefore it makes sense to get back glyph metrics in the same units. This is how a high-level API should work.

I think I will leave the autoscale system as it is.

**Comment by adrientetar** [comment]
But would it be possible to make autoscale constructor args default to False?

Right I now have to pass an additional False argument:

~~~
face = hb.Face.create_for_tables(
            _spitLayoutTable, layoutTables, None, False)

funcs = hb.FontFuncs.create(False)
~~~

So if Face and Font get their autoscale set to True when created from freetype object, why not make it default to False otherwise?

In FontFuncs, the autoscale argument can be inferred when `Font.set_funcs(funcs, ..)` (if autoscale is None the font sets its autoscale value to the FontFuncs).

**Comment by ldo** [comment]
The `Font.autoscale` and `FontFuncs.autoscale` settings are independent, and serve different purposes.

In fact, I’ve been thinking whether it might not be useful to generalize to other scale factors besides the shift of 6 used by FreeType.

But maybe I’ll just leave it this way for now.
