### ISSUE TITLE
The signature of python font funcs callbacks is different from C

### ISSUE THREAD

**Issue by khaledhosny** [ldo/harfpy#6]
Take for example glyph advance function, the documentation says:

>     def get_glyph_v_advance(self, font_data, glyph, user_data)
>      
> where self is the FontFuncs instance and font_data was what was passed to set_font_funcs for the Font, and return a float.

But in C the first argument in the font itself, which is needed here since the glyph advance (in font units) should be multiplied by the font scale.

**Comment by ldo** [comment]
No, this is not needed. You define the callbacks, you decide whether they return scaled floats or unscaled integers. HarfBuzz always wants unscaled integers, so it is up to my `FontFuncs` callback wrappers to convert things appropriately.

This should become clearer after I post my full fix for #3.

**Comment by ldo** [comment]
The full fix is now here: d88fbb2.

**Comment by khaledhosny** [comment]
Still not clear how my callback functions should return values that are specified in font design units (i.e. relative to UPEM), the C code would do the equivalent of the following:

    return value * font.scale[0] / font.face.upem

**Comment by ldo** [comment]
You can put what you like in the `font_data` and `user_data`; these can be general Python objects. That’s why I didn’t see the point in passing the font as well.

Note I don’t actually use HarfBuzz’s `user_data` support. And I use its `font_data` to pass the font, which I then use to find my own `font_data` object.

**Comment by khaledhosny** [comment]
I did that already, but it means I already use `font_data` for something else, so I had to use `user_data` for passing the HarfBuzz Font, but I feel this deviance from C API complicates things unnecessarily and the passed FontFuncs is always unused.

**Comment by ldo** [comment]
Yes, I think it makes more sense to pass the `Font` rather than the `FontFuncs` as the first arg to the callbacks. After all, the callbacks are not methods of the `FontFuncs`.

**Comment by ldo** [comment]
OK, done.
