### ISSUE TITLE
Blob from bytes?

### ISSUE THREAD

**Issue by adrientetar** [ldo/harfpy#7]
Are the following Blob declarations equivalent?

1.

~~~python
table = b'..' # the font table in bytes
blob = hb.Blob.create(
    table, len(table), HB.MEMORY_MODE_READONLY, None, None)
~~~

2.

~~~python
import array

table = b'..' # the font table in bytes
a = array.array('B')
a.frombytes(table)
value = hb.Blob.create_for_array(a, HB.MEMORY_MODE_READONLY)
~~~

The second example works, but the first one produces bad access. Am I missing something?

**Comment by adrientetar** [comment]
It seems I also need to keep a reference to the Face object when calling `hb.Face.create_for_tables(..)` otherwise I get `OSError: exception: privileged instruction` when calling hb_shape.

**Comment by adrientetar** [comment]
Still get some access violations after that..

~~~
Traceback (most recent call last):
  File "c:\users\admin\downloads\trufont\lib\trufont\controls\glyphCanvasView.py", line 342, in keyPressEvent
    self._redirectEvent(event, self._currentTool.keyPressEvent)
  File "c:\users\admin\downloads\trufont\lib\trufont\controls\glyphCanvasView.py", line 465, in _redirectEvent
    callback(event)
  File "c:\users\admin\downloads\trufont\lib\trufont\drawingTools\textTool.py", line 123, in keyPressEvent
    self.layoutLine.insert(text)
  File "c:\users\admin\downloads\trufont\lib\trufont\objects\layoutLine.py", line 100, in insert
    self.updateView()
  File "c:\users\admin\downloads\trufont\lib\trufont\objects\layoutLine.py", line 170, in updateView
    self._shapeAndSetText()
  File "c:\users\admin\downloads\trufont\lib\trufont\objects\layoutLine.py", line 149, in _shapeAndSetText
    records = self.engine.process(names)
  File "c:\users\admin\downloads\trufont\lib\trufont\objects\layoutEngine.py", line 256, in process
    hb.shape(self._hbFont, buf, list(self._fontFeatures.values()))
  File "c:\users\admin\downloads\harfpy\harfbuzz.py", line 4194, in shape
    hb.hb_shape(font._hbobj, buffer._hbobj, c_features, nr_features)
OSError: exception: access violation reading 0xBEE7AE64
~~~

**Comment by adrientetar** [comment]
Ah, apparently storing a reference to the `hb.FontFuncs` I use fixes the last access violation.

**Comment by ldo** [comment]
In other words, a `Font` object needs to keep a reference to the parent `Face`?

**Comment by adrientetar** [comment]
I think so in the create_for_tables case which is similar to create_for_array (a reference to the data source should be kept). It can be left to the user, but in that case it should probably be documented.

**Comment by khaledhosny** [comment]
`hb_font_t` keeps a reference of its `hb_face_t`, so I think the Python objects should do something similar.

**Comment by adrientetar** [comment]
sgtm. The Font.face method would then return the cached Face object, this would keep the source data alive.

**Comment by ldo** [comment]
OK, I have done this in 99b3562. See if it fixes the problem.

**Comment by adrientetar** [comment]
Thanks. I think the same should be done for FontFuncs, a reference to it should be stored when Font.set_funcs is called.

About my question in the first post, would you know how to use the hb.Blob.create rather than create for array? (see first post)

**Comment by ldo** [comment]
There is a subtlety to getting the memory address for `bytes` and `bytearray` objects. `Blob.create_for_array` can now accept these as of 5a887d5 (copying the same code I used in Qahirah, thanks to a tip from Eryk Sun). You can just use that, or you can look at the code to figure out how to do it with `Blob.create` for yourself.

**Comment by ldo** [comment]
`Font.font_funcs` and `Buffer.unicode_funcs` now have associated references saved to prevent premature disposal as of e5c5fe0.
