### ISSUE TITLE
segfault on python exit if I don't manually del hb_font instance

### ISSUE THREAD

**Issue by anthrotype** [ldo/harfpy#9]
Take this simple helloworld.py snippet:

```python
import freetype2
import harfbuzz as hb

ft = freetype2.Library()
text_line = "abc"
buf = hb.Buffer.create()
buf.add_str(text_line, 0, len(text_line))
buf.guess_segment_properties()
ft_face = ft.new_face("/Users/cosimolupo/Desktop/test.ttf")
ft_face.set_char_size(size=1, resolution=72)
hb_font = hb.Font.ft_create(ft_face)
hb.shape(hb_font, buf)
print(
    "buf.glyph_infos = %s\n\n"
    "glyph_positions = %s" % (
        buf.glyph_infos, buf.glyph_positions
    )
)
# if I don't delete hb_font, I get "Segmentation fault: 11"
del hb_font
```

I noticed that, if I don't manually delete the `hb_font` instance myself, python will abort with a `Segmentation fault 11` immediately before exit, while it's destroying the `__main__` module.

**Comment by ldo** [comment]
I notice similar things happen with this and my other bindings. Like you, the only workaround I could find was to strategically call `del` on certain objects.

I’m not sure why it happens: I suspect the ill-defined semantics of when exactly Python calls the `__del__` method at script termination; things disappear in an unpredictable order.

**Comment by anthrotype** [comment]
I wonder if registering an `atexit` function that automatically does the clean up could help in this situation.

https://docs.python.org/3.6/library/atexit.html

**Comment by ldo** [comment]
OK, I have tried (8a12691) adding an `atexit` handler. This simply gets rid of all `__del__` methods from my classes that have them. See if that makes things more reliable.

**Comment by ldo** [comment]
In my own testing it seems to work better now, so closing.

Thanks for the tip about `atexit`, by the way.
